// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import <Foundation/Foundation.h>
@class LGAddress;
@class LGBitcoinLikeAddress;


@interface LGAddress : NSObject

- (nullable NSString *)getDerivationPath;

- (nullable NSString *)toString;

- (nullable LGBitcoinLikeAddress *)asBitcoinLikeAddress;

+ (nullable LGAddress *)parse:(nonnull NSString *)address;

@end
